# Generated by Django 2.2.2 on 2019-06-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FASTQseq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nucSeq', models.TextField(blank=True)),
                ('qualityScores', models.TextField(blank=True)),
            ],
        ),
    ]
